package events

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	familytreepb "github.com/Bad-Utya/myforebears-backend/gen/go/familytree"
	"github.com/Bad-Utya/myforebears-backend/services/events/internal/domain/models"
	"github.com/Bad-Utya/myforebears-backend/services/events/internal/storage"
	"github.com/google/uuid"
)

var (
	ErrInvalidEventTypeID                      = errors.New("invalid event type id")
	ErrInvalidEventID                          = errors.New("invalid event id")
	ErrInvalidTreeID                           = errors.New("invalid tree id")
	ErrInvalidUserID                           = errors.New("invalid user id")
	ErrInvalidEventTypeName                    = errors.New("event type name is required")
	ErrInvalidPrimaryPersonsMode               = errors.New("invalid primary persons mode")
	ErrInvalidPrimaryPersonsCount              = errors.New("invalid primary persons count")
	ErrInvalidEventDate                        = errors.New("invalid event date")
	ErrInvalidEventDatePrecision               = errors.New("invalid event date precision")
	ErrInvalidEventDateBound                   = errors.New("invalid event date bound")
	ErrInvalidPrimaryPersons                   = errors.New("invalid primary persons for event type")
	ErrDuplicatePersonInParticipants           = errors.New("duplicate person in participants")
	ErrParticipantListsOverlap                 = errors.New("person cannot be both primary and additional participant")
	ErrEventTypeNotFound                       = errors.New("event type not found")
	ErrEventNotFound                           = errors.New("event not found")
	ErrForbidden                               = errors.New("forbidden")
	ErrCannotDeleteSystemEventType             = errors.New("system event type cannot be deleted")
	ErrEventTypeInUse                          = errors.New("event type is used by existing events")
	ErrEventTypeAlreadyExists                  = errors.New("event type with this name already exists")
	ErrCannotDeleteAutogeneratedEvent          = errors.New("autogenerated event cannot be deleted")
	ErrCannotModifyAutogeneratedPrimaryPersons = errors.New("primary persons cannot be modified for autogenerated event")
	marriageEventTypeID                        = "2c2f5f12-5476-4ef4-89df-85d0a6f4a6bc"
	divorceEventTypeID                         = "f1df881e-d7ec-4e97-9f47-4fd926e49532"
)

type FamilyTreeValidator interface {
	ValidatePersonsInTree(ctx context.Context, requestUserID int, treeID string, personIDs []string) error
	UpdatePartnerRelationshipStatus(ctx context.Context, requestUserID int, treeID string, personID1 string, personID2 string, status familytreepb.PartnerRelationshipStatus) error
}

type Service struct {
	log        *slog.Logger
	storage    storage.Storage
	familyTree FamilyTreeValidator
}

func New(log *slog.Logger, storage storage.Storage, familyTree FamilyTreeValidator) *Service {
	return &Service{log: log, storage: storage, familyTree: familyTree}
}

func (s *Service) CreateEventType(ctx context.Context, requestUserID int, name string, mode models.PrimaryPersonsMode, count int) (models.EventType, error) {
	const op = "service.events.CreateEventType"
	log := s.log.With(slog.String("op", op))

	log.Info("creating event type", slog.Int("request_user_id", requestUserID), slog.String("name", name))

	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return models.EventType{}, fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	normalizedName := strings.TrimSpace(name)
	if normalizedName == "" {
		log.Info("invalid event type name")
		return models.EventType{}, fmt.Errorf("%s: %w", op, ErrInvalidEventTypeName)
	}

	if !isValidPrimaryPersonsMode(mode) {
		log.Info("invalid primary persons mode", slog.String("mode", string(mode)))
		return models.EventType{}, fmt.Errorf("%s: %w", op, ErrInvalidPrimaryPersonsMode)
	}

	if mode == models.PrimaryPersonsModeFixed && count < 1 {
		log.Info("invalid primary persons count", slog.Int("count", count))
		return models.EventType{}, fmt.Errorf("%s: %w", op, ErrInvalidPrimaryPersonsCount)
	}
	if mode == models.PrimaryPersonsModeUnlimited {
		count = 0
	}

	now := time.Now()
	eventType := models.EventType{
		ID:                  uuid.New(),
		OwnerUserID:         requestUserID,
		IsSystem:            false,
		Name:                normalizedName,
		PrimaryPersonsMode:  mode,
		PrimaryPersonsCount: count,
		CreatedAt:           now,
		UpdatedAt:           now,
	}

	if err := s.storage.CreateEventType(ctx, eventType); err != nil {
		if errors.Is(err, storage.ErrEventTypeAlreadyExists) {
			log.Info("event type already exists", slog.String("name", normalizedName))
			return models.EventType{}, fmt.Errorf("%s: %w", op, ErrEventTypeAlreadyExists)
		}
		log.Error("failed to create event type", slog.String("error", err.Error()))
		return models.EventType{}, fmt.Errorf("%s: %w", op, err)
	}

	log.Info("event type created", slog.String("event_type_id", eventType.ID.String()))

	return eventType, nil
}

func (s *Service) DeleteEventType(ctx context.Context, requestUserID int, eventTypeID string) error {
	const op = "service.events.DeleteEventType"
	log := s.log.With(slog.String("op", op))

	log.Info("deleting event type", slog.Int("request_user_id", requestUserID), slog.String("event_type_id", eventTypeID))

	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	parsedEventTypeID, err := uuid.Parse(eventTypeID)
	if err != nil {
		log.Info("invalid event type id", slog.String("event_type_id", eventTypeID))
		return fmt.Errorf("%s: %w", op, ErrInvalidEventTypeID)
	}

	eventType, err := s.storage.GetEventType(ctx, parsedEventTypeID)
	if err != nil {
		if errors.Is(err, storage.ErrEventTypeNotFound) {
			log.Info("event type not found", slog.String("event_type_id", parsedEventTypeID.String()))
			return fmt.Errorf("%s: %w", op, ErrEventTypeNotFound)
		}
		log.Error("failed to load event type", slog.String("error", err.Error()))
		return fmt.Errorf("%s: %w", op, err)
	}

	if eventType.IsSystem {
		log.Info("attempt to delete system event type", slog.String("event_type_id", parsedEventTypeID.String()))
		return fmt.Errorf("%s: %w", op, ErrCannotDeleteSystemEventType)
	}

	if eventType.OwnerUserID != requestUserID {
		log.Info("forbidden event type delete", slog.Int("owner_user_id", eventType.OwnerUserID), slog.Int("request_user_id", requestUserID))
		return fmt.Errorf("%s: %w", op, ErrForbidden)
	}

	hasEvents, err := s.storage.HasEventsByType(ctx, parsedEventTypeID)
	if err != nil {
		log.Error("failed to check events by type", slog.String("error", err.Error()))
		return fmt.Errorf("%s: %w", op, err)
	}
	if hasEvents {
		log.Info("event type is in use", slog.String("event_type_id", parsedEventTypeID.String()))
		return fmt.Errorf("%s: %w", op, ErrEventTypeInUse)
	}

	if err := s.storage.DeleteEventType(ctx, parsedEventTypeID); err != nil {
		if errors.Is(err, storage.ErrEventTypeNotFound) {
			log.Info("event type not found during delete", slog.String("event_type_id", parsedEventTypeID.String()))
			return fmt.Errorf("%s: %w", op, ErrEventTypeNotFound)
		}
		log.Error("failed to delete event type", slog.String("error", err.Error()))
		return fmt.Errorf("%s: %w", op, err)
	}

	log.Info("event type deleted", slog.String("event_type_id", parsedEventTypeID.String()))

	return nil
}

func (s *Service) GetEventType(ctx context.Context, requestUserID int, eventTypeID string) (models.EventType, error) {
	const op = "service.events.GetEventType"
	log := s.log.With(slog.String("op", op))

	log.Info("getting event type", slog.Int("request_user_id", requestUserID), slog.String("event_type_id", eventTypeID))

	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return models.EventType{}, fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	parsedEventTypeID, err := uuid.Parse(eventTypeID)
	if err != nil {
		log.Info("invalid event type id", slog.String("event_type_id", eventTypeID))
		return models.EventType{}, fmt.Errorf("%s: %w", op, ErrInvalidEventTypeID)
	}

	eventType, err := s.loadAndAuthorizeEventType(ctx, op, requestUserID, parsedEventTypeID)
	if err != nil {
		log.Error("failed to get event type", slog.String("error", err.Error()))
		return models.EventType{}, err
	}

	log.Info("event type loaded", slog.String("event_type_id", eventType.ID.String()))

	return eventType, nil
}

func (s *Service) ListEventTypes(ctx context.Context, requestUserID int) ([]models.EventType, error) {
	const op = "service.events.ListEventTypes"
	log := s.log.With(slog.String("op", op))

	log.Info("listing event types", slog.Int("request_user_id", requestUserID))

	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return nil, fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	eventTypes, err := s.storage.ListEventTypesForUser(ctx, requestUserID)
	if err != nil {
		log.Error("failed to list event types", slog.String("error", err.Error()))
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	log.Info("event types listed", slog.Int("count", len(eventTypes)))

	return eventTypes, nil
}

func (s *Service) CreateEvent(
	ctx context.Context,
	requestUserID int,
	treeID string,
	eventTypeID string,
	primaryPersonIDs []string,
	additionalPersonIDs []string,
	dateISO string,
	datePrecision models.EventDatePrecision,
	dateBound models.EventDateBound,
	dateUnknown bool,
	isAutogenerated bool,
) (models.Event, error) {
	const op = "service.events.CreateEvent"
	log := s.log.With(slog.String("op", op))

	log.Info("creating event", slog.Int("request_user_id", requestUserID), slog.String("tree_id", treeID), slog.String("event_type_id", eventTypeID))

	parsedTreeID, parsedEventTypeID, parsedDate, err := s.parseAndValidateBaseInput(
		log,
		op,
		requestUserID,
		treeID,
		eventTypeID,
		dateISO,
		datePrecision,
		dateBound,
		dateUnknown,
	)
	if err != nil {
		return models.Event{}, err
	}

	eventType, err := s.loadAndAuthorizeEventType(ctx, op, requestUserID, parsedEventTypeID)
	if err != nil {
		log.Error("failed to authorize event type", slog.String("error", err.Error()))
		return models.Event{}, err
	}

	primaryParsed, additionalParsed, participantIDs, err := validateAndParseParticipants(primaryPersonIDs, additionalPersonIDs, eventType)
	if err != nil {
		log.Info("invalid participants", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	if err := s.familyTree.ValidatePersonsInTree(ctx, requestUserID, parsedTreeID.String(), participantIDs); err != nil {
		log.Error("failed to validate participants in tree", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	now := time.Now()
	event := models.Event{
		ID:                  uuid.New(),
		TreeID:              parsedTreeID,
		EventTypeID:         parsedEventTypeID,
		PrimaryPersonIDs:    primaryParsed,
		AdditionalPersonIDs: additionalParsed,
		DateValue:           parsedDate,
		DateUnknown:         dateUnknown,
		IsAutogenerated:     isAutogenerated,
		DatePrecision:       datePrecision,
		DateBound:           dateBound,
		CreatedAt:           now,
		UpdatedAt:           now,
	}

	if err := s.storage.CreateEvent(ctx, event); err != nil {
		log.Error("failed to create event", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	if shouldSyncPartnerStatus(event.EventTypeID, event.PrimaryPersonIDs, event.AdditionalPersonIDs) {
		if err := s.syncPartnerRelationshipStatusForPair(ctx, requestUserID, event.TreeID, event.PrimaryPersonIDs[0], event.PrimaryPersonIDs[1]); err != nil {
			log.Error("failed to sync partner relationship status", slog.String("error", err.Error()))
			return models.Event{}, fmt.Errorf("%s: %w", op, err)
		}
	}

	log.Info("event created", slog.String("event_id", event.ID.String()))

	return event, nil
}

func (s *Service) UpdateEvent(
	ctx context.Context,
	requestUserID int,
	eventID string,
	eventTypeID string,
	primaryPersonIDs []string,
	additionalPersonIDs []string,
	dateISO string,
	datePrecision models.EventDatePrecision,
	dateBound models.EventDateBound,
	dateUnknown bool,
) (models.Event, error) {
	const op = "service.events.UpdateEvent"
	log := s.log.With(slog.String("op", op))

	log.Info("updating event", slog.Int("request_user_id", requestUserID), slog.String("event_id", eventID), slog.String("event_type_id", eventTypeID))

	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return models.Event{}, fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	parsedEventID, err := uuid.Parse(eventID)
	if err != nil {
		log.Info("invalid event id", slog.String("event_id", eventID))
		return models.Event{}, fmt.Errorf("%s: %w", op, ErrInvalidEventID)
	}

	existing, err := s.storage.GetEvent(ctx, parsedEventID)
	if err != nil {
		if errors.Is(err, storage.ErrEventNotFound) {
			log.Info("event not found", slog.String("event_id", parsedEventID.String()))
			return models.Event{}, fmt.Errorf("%s: %w", op, ErrEventNotFound)
		}
		log.Error("failed to get event", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	parsedEventTypeID, err := uuid.Parse(eventTypeID)
	if err != nil {
		log.Info("invalid event type id", slog.String("event_type_id", eventTypeID))
		return models.Event{}, fmt.Errorf("%s: %w", op, ErrInvalidEventTypeID)
	}

	_, _, parsedDate, err := s.parseAndValidateBaseInput(log, op, requestUserID, existing.TreeID.String(), eventTypeID, dateISO, datePrecision, dateBound, dateUnknown)
	if err != nil {
		return models.Event{}, err
	}

	eventType, err := s.loadAndAuthorizeEventType(ctx, op, requestUserID, parsedEventTypeID)
	if err != nil {
		log.Error("failed to authorize event type", slog.String("error", err.Error()))
		return models.Event{}, err
	}

	primaryParsed, additionalParsed, participantIDs, err := validateAndParseParticipants(primaryPersonIDs, additionalPersonIDs, eventType)
	if err != nil {
		log.Info("invalid participants", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	if existing.IsAutogenerated && !equalUUIDSlices(existing.PrimaryPersonIDs, primaryParsed) {
		log.Info("attempt to modify autogenerated primary persons", slog.String("event_id", existing.ID.String()))
		return models.Event{}, fmt.Errorf("%s: %w", op, ErrCannotModifyAutogeneratedPrimaryPersons)
	}

	if err := s.familyTree.ValidatePersonsInTree(ctx, requestUserID, existing.TreeID.String(), participantIDs); err != nil {
		log.Error("failed to validate participants in tree", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	existing.EventTypeID = parsedEventTypeID
	existing.PrimaryPersonIDs = primaryParsed
	existing.AdditionalPersonIDs = additionalParsed
	existing.DateValue = parsedDate
	existing.DateUnknown = dateUnknown
	existing.DatePrecision = datePrecision
	existing.DateBound = dateBound
	existing.UpdatedAt = time.Now()

	if err := s.storage.UpdateEvent(ctx, existing); err != nil {
		if errors.Is(err, storage.ErrEventNotFound) {
			log.Info("event not found during update", slog.String("event_id", parsedEventID.String()))
			return models.Event{}, fmt.Errorf("%s: %w", op, ErrEventNotFound)
		}
		log.Error("failed to update event", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	log.Info("event updated", slog.String("event_id", existing.ID.String()))

	return existing, nil
}

func (s *Service) DeleteEvent(ctx context.Context, requestUserID int, eventID string) error {
	const op = "service.events.DeleteEvent"
	log := s.log.With(slog.String("op", op))

	log.Info("deleting event", slog.Int("request_user_id", requestUserID), slog.String("event_id", eventID))

	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	parsedEventID, err := uuid.Parse(eventID)
	if err != nil {
		log.Info("invalid event id", slog.String("event_id", eventID))
		return fmt.Errorf("%s: %w", op, ErrInvalidEventID)
	}

	event, err := s.storage.GetEvent(ctx, parsedEventID)
	if err != nil {
		if errors.Is(err, storage.ErrEventNotFound) {
			log.Info("event not found", slog.String("event_id", parsedEventID.String()))
			return fmt.Errorf("%s: %w", op, ErrEventNotFound)
		}
		log.Error("failed to get event", slog.String("error", err.Error()))
		return fmt.Errorf("%s: %w", op, err)
	}

	if err := s.familyTree.ValidatePersonsInTree(ctx, requestUserID, event.TreeID.String(), nil); err != nil {
		log.Error("failed to validate tree access", slog.String("error", err.Error()))
		return fmt.Errorf("%s: %w", op, err)
	}

	if event.IsAutogenerated {
		log.Info("attempt to delete autogenerated event", slog.String("event_id", event.ID.String()))
		return fmt.Errorf("%s: %w", op, ErrCannotDeleteAutogeneratedEvent)
	}

	if err := s.storage.DeleteEvent(ctx, parsedEventID); err != nil {
		if errors.Is(err, storage.ErrEventNotFound) {
			log.Info("event not found during delete", slog.String("event_id", parsedEventID.String()))
			return fmt.Errorf("%s: %w", op, ErrEventNotFound)
		}
		log.Error("failed to delete event", slog.String("error", err.Error()))
		return fmt.Errorf("%s: %w", op, err)
	}

	if shouldSyncPartnerStatus(event.EventTypeID, event.PrimaryPersonIDs, event.AdditionalPersonIDs) {
		if err := s.syncPartnerRelationshipStatusForPair(ctx, requestUserID, event.TreeID, event.PrimaryPersonIDs[0], event.PrimaryPersonIDs[1]); err != nil {
			log.Error("failed to sync partner relationship status", slog.String("error", err.Error()))
			return fmt.Errorf("%s: %w", op, err)
		}
	}

	log.Info("event deleted", slog.String("event_id", parsedEventID.String()))

	return nil
}

func (s *Service) GetEvent(ctx context.Context, requestUserID int, eventID string) (models.Event, error) {
	const op = "service.events.GetEvent"
	log := s.log.With(slog.String("op", op))

	log.Info("getting event", slog.Int("request_user_id", requestUserID), slog.String("event_id", eventID))

	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return models.Event{}, fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	parsedEventID, err := uuid.Parse(eventID)
	if err != nil {
		log.Info("invalid event id", slog.String("event_id", eventID))
		return models.Event{}, fmt.Errorf("%s: %w", op, ErrInvalidEventID)
	}

	event, err := s.storage.GetEvent(ctx, parsedEventID)
	if err != nil {
		if errors.Is(err, storage.ErrEventNotFound) {
			log.Info("event not found", slog.String("event_id", parsedEventID.String()))
			return models.Event{}, fmt.Errorf("%s: %w", op, ErrEventNotFound)
		}
		log.Error("failed to get event", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	if err := s.familyTree.ValidatePersonsInTree(ctx, requestUserID, event.TreeID.String(), nil); err != nil {
		log.Error("failed to validate tree access", slog.String("error", err.Error()))
		return models.Event{}, fmt.Errorf("%s: %w", op, err)
	}

	log.Info("event loaded", slog.String("event_id", event.ID.String()))

	return event, nil
}

func (s *Service) ListEventsByTree(ctx context.Context, requestUserID int, treeID string) ([]models.Event, error) {
	const op = "service.events.ListEventsByTree"
	log := s.log.With(slog.String("op", op))

	log.Info("listing events by tree", slog.Int("request_user_id", requestUserID), slog.String("tree_id", treeID))

	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return nil, fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	parsedTreeID, err := uuid.Parse(treeID)
	if err != nil {
		log.Info("invalid tree id", slog.String("tree_id", treeID))
		return nil, fmt.Errorf("%s: %w", op, ErrInvalidTreeID)
	}

	if err := s.familyTree.ValidatePersonsInTree(ctx, requestUserID, parsedTreeID.String(), nil); err != nil {
		log.Error("failed to validate tree access", slog.String("error", err.Error()))
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	events, err := s.storage.ListEventsByTree(ctx, parsedTreeID)
	if err != nil {
		log.Error("failed to list events by tree", slog.String("error", err.Error()))
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	log.Info("events listed", slog.Int("count", len(events)))

	return events, nil
}

func (s *Service) parseAndValidateBaseInput(
	log *slog.Logger,
	op string,
	requestUserID int,
	treeID string,
	eventTypeID string,
	dateISO string,
	datePrecision models.EventDatePrecision,
	dateBound models.EventDateBound,
	dateUnknown bool,
) (uuid.UUID, uuid.UUID, *time.Time, error) {
	if requestUserID <= 0 {
		log.Info("invalid request user id", slog.Int("request_user_id", requestUserID))
		return uuid.Nil, uuid.Nil, nil, fmt.Errorf("%s: %w", op, ErrInvalidUserID)
	}

	parsedTreeID, err := uuid.Parse(treeID)
	if err != nil {
		log.Info("invalid tree id", slog.String("tree_id", treeID))
		return uuid.Nil, uuid.Nil, nil, fmt.Errorf("%s: %w", op, ErrInvalidTreeID)
	}

	parsedEventTypeID, err := uuid.Parse(eventTypeID)
	if err != nil {
		log.Info("invalid event type id", slog.String("event_type_id", eventTypeID))
		return uuid.Nil, uuid.Nil, nil, fmt.Errorf("%s: %w", op, ErrInvalidEventTypeID)
	}

	if !isValidEventDatePrecision(datePrecision) {
		log.Info("invalid event date precision", slog.String("date_precision", string(datePrecision)))
		return uuid.Nil, uuid.Nil, nil, fmt.Errorf("%s: %w", op, ErrInvalidEventDatePrecision)
	}
	if !isValidEventDateBound(dateBound) {
		log.Info("invalid event date bound", slog.String("date_bound", string(dateBound)))
		return uuid.Nil, uuid.Nil, nil, fmt.Errorf("%s: %w", op, ErrInvalidEventDateBound)
	}

	if dateUnknown {
		return parsedTreeID, parsedEventTypeID, nil, nil
	}

	parsedDate, err := time.Parse("2006-01-02", dateISO)
	if err != nil {
		log.Info("invalid event date", slog.String("date_iso", dateISO))
		return uuid.Nil, uuid.Nil, nil, fmt.Errorf("%s: %w", op, ErrInvalidEventDate)
	}

	return parsedTreeID, parsedEventTypeID, &parsedDate, nil
}

func equalUUIDSlices(left []uuid.UUID, right []uuid.UUID) bool {
	if len(left) != len(right) {
		return false
	}

	for i := range left {
		if left[i] != right[i] {
			return false
		}
	}

	return true
}

func (s *Service) loadAndAuthorizeEventType(ctx context.Context, op string, requestUserID int, eventTypeID uuid.UUID) (models.EventType, error) {
	log := s.log.With(slog.String("op", op))

	eventType, err := s.storage.GetEventType(ctx, eventTypeID)
	if err != nil {
		if errors.Is(err, storage.ErrEventTypeNotFound) {
			log.Info("event type not found", slog.String("event_type_id", eventTypeID.String()))
			return models.EventType{}, fmt.Errorf("%s: %w", op, ErrEventTypeNotFound)
		}
		log.Error("failed to load event type", slog.String("error", err.Error()))
		return models.EventType{}, fmt.Errorf("%s: %w", op, err)
	}

	if !eventType.IsSystem && eventType.OwnerUserID != requestUserID {
		log.Info("forbidden event type access", slog.Int("owner_user_id", eventType.OwnerUserID), slog.Int("request_user_id", requestUserID))
		return models.EventType{}, fmt.Errorf("%s: %w", op, ErrForbidden)
	}

	return eventType, nil
}

func validateAndParseParticipants(primary []string, additional []string, eventType models.EventType) ([]uuid.UUID, []uuid.UUID, []string, error) {
	if !isValidPrimaryPersonsMode(eventType.PrimaryPersonsMode) {
		return nil, nil, nil, ErrInvalidPrimaryPersonsMode
	}

	if len(primary) == 0 {
		return nil, nil, nil, ErrInvalidPrimaryPersons
	}

	if eventType.PrimaryPersonsMode == models.PrimaryPersonsModeFixed && len(primary) != eventType.PrimaryPersonsCount {
		return nil, nil, nil, ErrInvalidPrimaryPersons
	}

	parsedPrimary := make([]uuid.UUID, 0, len(primary))
	parsedAdditional := make([]uuid.UUID, 0, len(additional))
	forValidation := make([]string, 0, len(primary)+len(additional))

	seenPrimary := make(map[uuid.UUID]struct{}, len(primary))
	for _, raw := range primary {
		parsedID, err := uuid.Parse(raw)
		if err != nil {
			return nil, nil, nil, ErrInvalidPrimaryPersons
		}
		if _, ok := seenPrimary[parsedID]; ok {
			return nil, nil, nil, ErrDuplicatePersonInParticipants
		}
		seenPrimary[parsedID] = struct{}{}
		parsedPrimary = append(parsedPrimary, parsedID)
		forValidation = append(forValidation, parsedID.String())
	}

	seenAdditional := make(map[uuid.UUID]struct{}, len(additional))
	for _, raw := range additional {
		parsedID, err := uuid.Parse(raw)
		if err != nil {
			return nil, nil, nil, ErrInvalidPrimaryPersons
		}
		if _, ok := seenPrimary[parsedID]; ok {
			return nil, nil, nil, ErrParticipantListsOverlap
		}
		if _, ok := seenAdditional[parsedID]; ok {
			return nil, nil, nil, ErrDuplicatePersonInParticipants
		}
		seenAdditional[parsedID] = struct{}{}
		parsedAdditional = append(parsedAdditional, parsedID)
		forValidation = append(forValidation, parsedID.String())
	}

	return parsedPrimary, parsedAdditional, forValidation, nil
}

func isValidPrimaryPersonsMode(mode models.PrimaryPersonsMode) bool {
	return mode == models.PrimaryPersonsModeFixed || mode == models.PrimaryPersonsModeUnlimited
}

func isValidEventDatePrecision(precision models.EventDatePrecision) bool {
	return precision == models.EventDatePrecisionDay ||
		precision == models.EventDatePrecisionMonth ||
		precision == models.EventDatePrecisionYear
}

func isValidEventDateBound(bound models.EventDateBound) bool {
	return bound == models.EventDateBoundExact ||
		bound == models.EventDateBoundNotBefore ||
		bound == models.EventDateBoundNotAfter
}

func shouldSyncPartnerStatus(eventTypeID uuid.UUID, primaryPersonIDs []uuid.UUID, additionalPersonIDs []uuid.UUID) bool {
	if len(primaryPersonIDs) != 2 || len(additionalPersonIDs) != 0 {
		return false
	}

	eventType := eventTypeID.String()
	return eventType == marriageEventTypeID || eventType == divorceEventTypeID
}

func (s *Service) syncPartnerRelationshipStatusForPair(ctx context.Context, requestUserID int, treeID uuid.UUID, personID1 uuid.UUID, personID2 uuid.UUID) error {
	events, err := s.storage.ListEventsByTree(ctx, treeID)
	if err != nil {
		return err
	}

	status := familytreepb.PartnerRelationshipStatus_PARTNER_RELATIONSHIP_STATUS_UNMARRIED
	latest := latestMaritalEventForPair(events, personID1, personID2)
	if latest != nil {
		switch latest.EventTypeID.String() {
		case marriageEventTypeID:
			status = familytreepb.PartnerRelationshipStatus_PARTNER_RELATIONSHIP_STATUS_MARRIED
		case divorceEventTypeID:
			status = familytreepb.PartnerRelationshipStatus_PARTNER_RELATIONSHIP_STATUS_DIVORCED
		}
	}

	return s.familyTree.UpdatePartnerRelationshipStatus(
		ctx,
		requestUserID,
		treeID.String(),
		personID1.String(),
		personID2.String(),
		status,
	)
}

func latestMaritalEventForPair(events []models.Event, personID1 uuid.UUID, personID2 uuid.UUID) *models.Event {
	var latest *models.Event

	for i := range events {
		event := &events[i]
		if event.EventTypeID.String() != marriageEventTypeID && event.EventTypeID.String() != divorceEventTypeID {
			continue
		}
		if len(event.PrimaryPersonIDs) != 2 || len(event.AdditionalPersonIDs) != 0 {
			continue
		}

		first := event.PrimaryPersonIDs[0]
		second := event.PrimaryPersonIDs[1]
		if !((first == personID1 && second == personID2) || (first == personID2 && second == personID1)) {
			continue
		}

		if latest == nil || isLaterMaritalEvent(event, latest) {
			latest = event
		}
	}

	return latest
}

func isLaterMaritalEvent(left *models.Event, right *models.Event) bool {
	if left.DateValue != nil && right.DateValue != nil {
		if left.DateValue.After(*right.DateValue) {
			return true
		}
		if left.DateValue.Before(*right.DateValue) {
			return false
		}
	}

	if left.DateValue != nil && right.DateValue == nil {
		return true
	}
	if left.DateValue == nil && right.DateValue != nil {
		return false
	}

	if left.CreatedAt.After(right.CreatedAt) {
		return true
	}
	if left.CreatedAt.Before(right.CreatedAt) {
		return false
	}

	return left.ID.String() > right.ID.String()
}
