version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: auth-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: auth_local_db

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_user -d auth_local_db"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7
    container_name: auth-redis
    restart: unless-stopped

    command: redis-server --requirepass local_password

    ports:
      - "6379:6379"

    volumes:
      - redisdata:/data

    healthcheck:
      test: ["CMD", "redis-cli", "-a", "local_password", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: emailprovider-rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: local_user
      RABBITMQ_DEFAULT_PASS: local_password

    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI

    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
