env: "local"
grpc:
  port: 50053
  timeout: 10h
postgres:
  host: "postgres"
  port: 5432
  username: "local_user"
  password: "local_password"
  database: "events_local_db"
familytree:
  address: "familytree:50052"
  timeout: 5s
  retries_count: 3
