env: "local"
access_token_ttl: 15m
refresh_token_ttl: 720h
user_storage:
  host: "postgres"
  port: 5432
  username: "from-env"
  password: "from-env"
  database: "auth_local_db"
verification_storage:
  address: "redis:6379"
  password: "from-env"
  database: 1
grpc:
  port: 50051
  timeout: 10h
link_for_reset_password: "http://localhost:3000/reset-password?token=%s"
link_ttl: 15m
rabbitmq:
  url: "from-env"
  exchange: "email"
  routing_key: "email.send"
