env: "local"
http:
  port: 8080
  timeout: 10s
  idle_timeout: 60s
clients:
  auth:
    address: "localhost:50051"
    timeout: 5s
    retries_count: 3
  token_storage:
    address: "localhost:6379"
    password: "local_password"
    database: 1
