ALTER TABLE events
    DROP CONSTRAINT IF EXISTS chk_events_date_state;

UPDATE events
SET
    date_value = COALESCE(date_value, CURRENT_DATE),
    date_unknown = FALSE
WHERE date_value IS NULL OR date_unknown = TRUE;

ALTER TABLE events
    ALTER COLUMN date_value SET NOT NULL;

ALTER TABLE events
    DROP COLUMN IF EXISTS is_autogenerated,
    DROP COLUMN IF EXISTS date_unknown;
