ALTER TABLE events
    ADD COLUMN IF NOT EXISTS date_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_autogenerated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE events
    ALTER COLUMN date_value DROP NOT NULL;

ALTER TABLE events
    DROP CONSTRAINT IF EXISTS chk_events_date_state;

ALTER TABLE events
    ADD CONSTRAINT chk_events_date_state
    CHECK (
        (date_unknown = TRUE AND date_value IS NULL)
        OR
        (date_unknown = FALSE AND date_value IS NOT NULL)
    );
